CC = gcc
CFLAGS = -I../include -c
LFLAGS = -L../lib -lpthread -lmath
TARGET = aaa
OBJS = main.o add.o

$(TARGET): $(OBJS)
	$(CC) $(OBJS) -o $(TARGET) $(LFLAGS)

#.c.o:
# new 
# new stylestyle
%.o : %.c
	$(CC) $(CFLAGS) $< 

clean:
	rm -f $(OBJS) $(TARGET)
